# These are supported funding model platforms

github: [Raz-js]
patreon: # Replace with a single Patreon username
ko_fi: # Replace with a single Ko-fi username
paypal: ['https://paypal.me/razebr']
custom: ['https://paypal.me/razebr']
